# Generated by Django 5.1 on 2024-09-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='added_date',
            field=models.DateTimeField(),
        ),
    ]
